FROM node:16

# RUN mkdir /home/node/app

WORKDIR /home/node/app

# COPY . /home/node/app
# COPY package.json package-lock.json ./
COPY package.json ./

RUN npm install
#necessário o run build com o dev? Acho que não
# RUN npm run build
# RUN npm run dev
# COPY --from=node:16 /usr/src/home/node/app/node_modules node_modules


# COPY --from=build-target /usr/src/app/.next .next

# CMD ["npm","start"]

# CMD ["npm","run dev"]

# ENTRYPOINT ["nodemon", "/usr/src/app/server.js"]